// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { createNote, listNotes, type Options } from '../sdk.gen';
import type { CreateNoteData, CreateNoteError, CreateNoteResponse, ListNotesData, ListNotesError, ListNotesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listNotesQueryKey = (options?: Options<ListNotesData>) => createQueryKey('listNotes', options);

/**
 * List notes, newest first
 *
 * Returns at most `limit` notes, newest first.
 */
export const listNotesOptions = (options?: Options<ListNotesData>) => queryOptions<ListNotesResponse, ListNotesError, ListNotesResponse, ReturnType<typeof listNotesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listNotes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listNotesQueryKey(options)
});

/**
 * Create a note
 *
 * Stores a note and returns it with its id and creation time.
 */
export const createNoteMutation = (options?: Partial<Options<CreateNoteData>>): UseMutationOptions<CreateNoteResponse, CreateNoteError, Options<CreateNoteData>> => {
    const mutationOptions: UseMutationOptions<CreateNoteResponse, CreateNoteError, Options<CreateNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
