// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleForwardAuth handles forwardAuth security.
	// Set by the platform's forward-auth at the edge, never by a client. The server refuses a request
	// without it; on a local run DEV_USER fills it in.
	HandleForwardAuth(ctx context.Context, operationName OperationName, t ForwardAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesForwardAuth is a private map storing roles per operation.
var operationRolesForwardAuth = map[string][]string{
	CreateNoteOperation: []string{},
	ListNotesOperation:  []string{},
}

// GetRolesForForwardAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForForwardAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForForwardAuth(operation string) []string {
	roles, ok := operationRolesForwardAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityForwardAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ForwardAuth
	const parameterName = "X-User-Id"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesForwardAuth[operationName]
	rctx, err := s.sec.HandleForwardAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ForwardAuth provides forwardAuth security value.
	// Set by the platform's forward-auth at the edge, never by a client. The server refuses a request
	// without it; on a local run DEV_USER fills it in.
	ForwardAuth(ctx context.Context, operationName OperationName) (ForwardAuth, error)
}

func (s *Client) securityForwardAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ForwardAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ForwardAuth\"")
	}
	req.Header.Set("X-User-Id", t.APIKey)
	return nil
}
