// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements createNote operation.
	//
	// Stores a note and returns it with its id and creation time.
	//
	// POST /api/v1/notes
	CreateNote(ctx context.Context, req *NewNote) (CreateNoteRes, error)
	// ListNotes implements listNotes operation.
	//
	// Returns at most `limit` notes, newest first.
	//
	// GET /api/v1/notes
	ListNotes(ctx context.Context, params ListNotesParams) (ListNotesRes, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
