// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements createNote operation.
//
// Stores a note and returns it with its id and creation time.
//
// POST /api/v1/notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *NewNote) (r CreateNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNotes implements listNotes operation.
//
// Returns at most `limit` notes, newest first.
//
// GET /api/v1/notes
func (UnimplementedHandler) ListNotes(ctx context.Context, params ListNotesParams) (r ListNotesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
