// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateNoteData, CreateNoteErrors, CreateNoteResponses, ListNotesData, ListNotesErrors, ListNotesResponses } from './types.gen';
import { zCreateNoteBody, zCreateNoteResponse, zListNotesQuery, zListNotesResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List notes, newest first
 *
 * Returns at most `limit` notes, newest first.
 */
export const listNotes = <ThrowOnError extends boolean = false>(options?: Options<ListNotesData, ThrowOnError>): RequestResult<ListNotesResponses, ListNotesErrors, ThrowOnError> => (options?.client ?? client).get<ListNotesResponses, ListNotesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zListNotesQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListNotesResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/notes',
    ...options
});

/**
 * Create a note
 *
 * Stores a note and returns it with its id and creation time.
 */
export const createNote = <ThrowOnError extends boolean = false>(options: Options<CreateNoteData, ThrowOnError>): RequestResult<CreateNoteResponses, CreateNoteErrors, ThrowOnError> => (options.client ?? client).post<CreateNoteResponses, CreateNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateNoteBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateNoteResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
