// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://template-go-vue.jorisjonkers.dev' | (string & {});
};

/**
 * A note to create.
 */
export type NewNote = {
    /**
     * The note's text.
     */
    text: string;
};

/**
 * A stored note.
 */
export type Note = {
    /**
     * The note's id.
     */
    id: string;
    /**
     * The note's text.
     */
    text: string;
    /**
     * When the note was stored.
     */
    createdAt: string;
};

/**
 * A page of notes, newest first.
 */
export type NoteList = {
    /**
     * The notes.
     */
    items: Array<Note>;
};

/**
 * An RFC 9457 problem detail.
 */
export type Problem = {
    /**
     * A URI naming the problem type.
     */
    type: string;
    /**
     * A short summary of the problem type.
     */
    title: string;
    /**
     * The HTTP status code.
     */
    status: number;
    /**
     * What went wrong in this occurrence.
     */
    detail?: string;
};

export type ListNotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * How many notes to return.
         */
        limit?: number;
    };
    url: '/api/v1/notes';
};

export type ListNotesErrors = {
    /**
     * An RFC 9457 problem.
     */
    400: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type ListNotesError = ListNotesErrors[keyof ListNotesErrors];

export type ListNotesResponses = {
    /**
     * The notes.
     */
    200: NoteList;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
    body: NewNote;
    path?: never;
    query?: never;
    url: '/api/v1/notes';
};

export type CreateNoteErrors = {
    /**
     * An RFC 9457 problem.
     */
    400: Problem;
    /**
     * An RFC 9457 problem.
     */
    422: Problem;
    /**
     * An RFC 9457 problem.
     */
    default: Problem;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
    /**
     * The created note.
     */
    201: Note;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];
