// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * A note to create.
 */
export const zNewNote = z.object({
    text: z.string().min(1).max(500)
});

/**
 * A stored note.
 */
export const zNote = z.object({
    id: z.uuid().max(36),
    text: z.string().min(1).max(500),
    createdAt: z.iso.datetime({ offset: true }).max(64)
});

/**
 * A page of notes, newest first.
 */
export const zNoteList = z.object({
    items: z.array(zNote).max(100)
});

/**
 * An RFC 9457 problem detail.
 */
export const zProblem = z.object({
    type: z.string().max(256),
    title: z.string().max(256),
    status: z.int().gte(100).lte(599),
    detail: z.string().max(1024).optional()
});

export const zListNotesQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(50)
});

/**
 * The notes.
 */
export const zListNotesResponse = zNoteList;

export const zCreateNoteBody = zNewNote;

/**
 * The created note.
 */
export const zCreateNoteResponse = zNote;
