// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package queries

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (text) VALUES ($1)
RETURNING id, text, created_at
`

func (q *Queries) CreateNote(ctx context.Context, text string) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, text)
	var i Note
	err := row.Scan(&i.ID, &i.Text, &i.CreatedAt)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, text, created_at
FROM notes
ORDER BY created_at DESC, id
LIMIT $1
`

func (q *Queries) ListNotes(ctx context.Context, limit int32) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Text, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
