// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, text string) (Note, error)
	ListNotes(ctx context.Context, limit int32) ([]Note, error)
}

var _ Querier = (*Queries)(nil)
